name: Release Gem
on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.*'

jobs:
  release:
    name: Build and push to GitHub Package Registry
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1

      - name: Set GitHub credentials
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:github: Bearer ${{ github.token }}\n" > $HOME/.gem/credentials

      - name: Build Gem
        run: gem build *.gemspec

      - name: Push Gem to GitHub Packages
        run: gem push --KEY github --host https://rubygems.pkg.github.com/${{ github.repository_owner }} *.gem
